<?php
declare(strict_types=1);
require_once __DIR__ . '/_university_shell.php';
$q=trim((string)($_GET['q']??''));$status=strtoupper((string)($_GET['status']??'ALL'));
$allowed=['ALL','BOOKED','CONFIRMED','TRANSFER_PENDING','CANCELLED','COMPLETED'];if(!in_array($status,$allowed,true))$status='ALL';
$sql="SELECT DISTINCT bk.booking_id,bk.booking_reference,bk.slot_type,bk.seat_number,bk.standing_slot,bk.fare_charged,bk.status,bk.booking_date,p.name passenger_name,p.passenger_type,r.route_code,r.route_name,s.schedule_date,s.departure_time FROM bookings bk JOIN passengers p ON p.passenger_id=bk.passenger_id JOIN schedules s ON s.schedule_id=bk.schedule_id JOIN routes r ON r.route_id=s.route_id WHERE p.university_id=? AND r.university_id=?";$params=[$uUniversityId,$uUniversityId];
if($q!==''){$sql.=" AND (bk.booking_reference LIKE ? OR p.name LIKE ? OR r.route_code LIKE ?)";$like='%'.$q.'%';array_push($params,$like,$like,$like);}if($status!=='ALL'){$sql.=" AND bk.status=?";$params[]=$status;}$sql.=" ORDER BY bk.booking_date DESC LIMIT 250";
$rows=[];try{$rows=u_all($pdo,$sql,$params);}catch(Throwable $e){error_log('[UniRide bookings] '.$e->getMessage());}
u_render_start('Bookings','bookings','Operations','Booking records associated with this university’s passengers and schedules.');u_render_actions('<a class="up-button-secondary" href="occupancy.php">View Occupancy</a>');u_render_heading_end();
?>
<form method="get" class="up-filter"><input type="search" name="q" value="<?= u_h($q) ?>" placeholder="Booking reference, passenger or route"><select name="status"><?php foreach($allowed as $s): ?><option value="<?= u_h($s) ?>" <?= $s===$status?'selected':'' ?>><?= u_h($s) ?></option><?php endforeach; ?></select><button class="up-button-secondary" type="submit">Filter</button></form>
<?php if(!$rows): ?><div class="up-empty"><div><strong>No matching bookings.</strong><p>Passenger bookings for this university will appear here.</p></div></div><?php else: ?><div class="up-table-wrap"><table class="up-table"><thead><tr><th>Reference</th><th>Passenger</th><th>Route</th><th>Schedule</th><th>Seat / Slot</th><th>Fare</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?= u_h($r['booking_reference']) ?></strong><small><?= u_h(u_date($r['booking_date'],'d M · g:i A')) ?></small></td><td><strong><?= u_h($r['passenger_name']) ?></strong><small><?= u_h(ucfirst(strtolower($r['passenger_type']))) ?></small></td><td><?= u_h($r['route_code']) ?></td><td><?= u_h(u_date($r['schedule_date'],'d M')) ?> · <?= u_h(u_time($r['departure_time'])) ?></td><td><?= u_h(u_seat_label($r)) ?></td><td>৳<?= number_format((float)$r['fare_charged'],0) ?></td><td><span class="up-status <?= u_h(u_status_class($r['status'])) ?>"><?= u_h($r['status']) ?></span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
<?php u_render_end(); ?>
